export enum CriteriaName {
    COMPELLING_EMOTIONAL_CONTENT = "COMPELLING_EMOTIONAL_CONTENT",
    DEMONSTRATED_SYSTEMIC_IMPACT = "DEMONSTRATED_SYSTEMIC_IMPACT",
    STRONG_EXECUTIVE_PRESENCE = "STRONG_EXECUTIVE_PRESENCE"
}