export enum SocketEvents{
    CONNECT = "connect",
    MESSAGE = "MESSAGE",
    HELLO = "HELLO",
    DISCONNECT = "disconnect",
    SUBMIT_TO_SHEET = "SUBMIT_TO_SHEET",
    SIGN_IN = "SIGN_IN",
    SIGN_OUT = "SIGN_OUT",
    SELECT_TEAM = "SELECT_TEAM",
    DASHBOARD_UPDATED = "DASHBOARD_UPDATED",
    UPDATE_TEAM = "UPDATE_TEAM",
    TEAM_UPDATED = "TEAM_UPDATED",
    GAME_STATE_CHANGED = "GAME_STATE_CHANGED",
    JOIN_ROOM = "JOIN_ROOM",
    ROOM_MESSAGE = "ROOM_MESSAGE"
}